/*
 * Permit.io PDP
 *
 * The PDP (Policy decision point) container wraps Open Policy Agent (OPA) with a higher-level API intended for fine grained application-level authorization. The PDP automatically handles pulling policy updates in real-time from a centrally managed cloud-service (api.permit.io).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AuthorizationQueryV1 : the format of is_allowed() input
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizationQueryV1 {
    #[serde(rename = "user")]
    pub user: String,
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "resource")]
    pub resource: Box<models::ResourceV1>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
}

impl AuthorizationQueryV1 {
    /// the format of is_allowed() input
    pub fn new(user: String, action: String, resource: models::ResourceV1) -> AuthorizationQueryV1 {
        AuthorizationQueryV1 {
            user,
            action,
            resource: Box::new(resource),
            context: None,
        }
    }
}

