/*
 * Permit.io PDP
 *
 * The PDP (Policy decision point) container wraps Open Policy Agent (OPA) with a higher-level API intended for fine grained application-level authorization. The PDP automatically handles pulling policy updates in real-time from a centrally managed cloud-service (api.permit.io).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KongAuthorizationInputConsumer {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "username")]
    pub username: String,
}

impl KongAuthorizationInputConsumer {
    pub fn new(id: uuid::Uuid, username: String) -> KongAuthorizationInputConsumer {
        KongAuthorizationInputConsumer {
            id,
            username,
        }
    }
}

