/*
 * Permit.io PDP
 *
 * The PDP (Policy decision point) container wraps Open Policy Agent (OPA) with a higher-level API intended for fine grained application-level authorization. The PDP automatically handles pulling policy updates in real-time from a centrally managed cloud-service (api.permit.io).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// KongAuthorizationQuery : the format of is_allowed_kong() input
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KongAuthorizationQuery {
    #[serde(rename = "input")]
    pub input: Box<models::KongAuthorizationInput>,
}

impl KongAuthorizationQuery {
    /// the format of is_allowed_kong() input
    pub fn new(input: models::KongAuthorizationInput) -> KongAuthorizationQuery {
        KongAuthorizationQuery {
            input: Box::new(input),
        }
    }
}

