/*
 * Permit.io PDP
 *
 * The PDP (Policy decision point) container wraps Open Policy Agent (OPA) with a higher-level API intended for fine grained application-level authorization. The PDP automatically handles pulling policy updates in real-time from a centrally managed cloud-service (api.permit.io).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KongAuthorizationInputRequest {
    #[serde(rename = "http")]
    pub http: Box<models::KongAuthorizationInputRequestHttp>,
}

impl KongAuthorizationInputRequest {
    pub fn new(http: models::KongAuthorizationInputRequestHttp) -> KongAuthorizationInputRequest {
        KongAuthorizationInputRequest {
            http: Box::new(http),
        }
    }
}

