/*
 * Permit.io PDP
 *
 * The PDP (Policy decision point) container wraps Open Policy Agent (OPA) with a higher-level API intended for fine grained application-level authorization. The PDP automatically handles pulling policy updates in real-time from a centrally managed cloud-service (api.permit.io).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PolicyStoreTypes : An enumeration.
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PolicyStoreTypes {
    #[serde(rename = "OPA")]
    Opa,
    #[serde(rename = "MOCK")]
    Mock,

}

impl ToString for PolicyStoreTypes {
    fn to_string(&self) -> String {
        match self {
            Self::Opa => String::from("OPA"),
            Self::Mock => String::from("MOCK"),
        }
    }
}

impl Default for PolicyStoreTypes {
    fn default() -> PolicyStoreTypes {
        Self::Opa
    }
}

