/*
 * Permit.io PDP
 *
 * The PDP (Policy decision point) container wraps Open Policy Agent (OPA) with a higher-level API intended for fine grained application-level authorization. The PDP automatically handles pulling policy updates in real-time from a centrally managed cloud-service (api.permit.io).
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UrlAuthorizationQuery : the format of is_allowed_url() input
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UrlAuthorizationQuery {
    #[serde(rename = "user")]
    pub user: Box<models::User>,
    #[serde(rename = "http_method")]
    pub http_method: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "tenant")]
    pub tenant: String,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
    #[serde(rename = "sdk", skip_serializing_if = "Option::is_none")]
    pub sdk: Option<String>,
}

impl UrlAuthorizationQuery {
    /// the format of is_allowed_url() input
    pub fn new(user: models::User, http_method: String, url: String, tenant: String) -> UrlAuthorizationQuery {
        UrlAuthorizationQuery {
            user: Box::new(user),
            http_method,
            url,
            tenant,
            context: None,
            sdk: None,
        }
    }
}

